app/__init__.py
import urllib3
from flask import Flask, render_template
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def register_custom_error(app):

    @app.errorhandler(403)
    def page_authorization_error(e):
        return render_template('error/page-403.html'), 403

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('error/page-404.html'), 404

    @app.errorhandler(500)
    def page_internal_error(e):
        return render_template('error/page-500.html'), 500


def register_blueprints(app):
    for module_name in ('auth', 'dashboard', 'vms', 'marketplace'):
        module = import_module(f'app.{module_name}')
        app.register_blueprint(module.blueprint)


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)

    register_extensions(app)
    configure_database(app)
    register_custom_error(app)
    register_blueprints(app)

    # disable ssl warning if SSL_VERIFY is disabled
    if not app.config['SSL_VERIFY']:
        urllib3.disable_warnings()

    return app

app/dashboard/__init__.py
from flask import Blueprint

blueprint = Blueprint('dashboard',
                      __name__,
                      url_prefix='')

from . import views

app/dashboard/views.py
from flask import render_template, request, current_app
from flask_login import login_required, current_user
from werkzeug.utils import redirect
from . import blueprint
from .utils import list_deployed_apps, project_meter


@blueprint.route('/')
@login_required
def index():
    current_app.logger.debug('Entering dashboard.index view')
    deployed_apps = list_deployed_apps(current_user)
    usage = project_meter (current_user)
    current_app.logger.debug('Returning dashboard.index Template')
    return render_template('dashboard/index.html', segment=['dashboard'], apps=deployed_apps, usage=usage)

@blueprint.route('/taskselect/<task>', methods= ['GET'])
@login_required
def taskselect(task):
    if task == 'vm':
        return redirect('/marketplace')

app/marketplace/__init__.py
from flask import Blueprint

blueprint = Blueprint('marketplace',
                      __name__,
                      url_prefix='/marketplace')

from . import views

app/marketplace/views.py
from flask import render_template, request
from flask_login import login_required, current_user
from werkzeug.utils import redirect
from wtforms.fields.core import UnboundField
from . import blueprint
from .utils import launch_mpi, list_marketplace_items, get_runtime_editables

@blueprint.route('/')
@login_required
def index():
    available_items = list_marketplace_items(current_user)
    return render_template('marketplace/index.html', segment=['virtual_machines'], mpi_list=available_items)

@blueprint.route('/deploy', methods= ['GET','POST'])
@login_required
def deploy():
    if request.method == "POST":
        app_name = request.form['mpi_app_name']
        f = request.form
        runtime_editables=[]
        for key in f.keys():
            if key != 'mpi_app_name':
                for value in f.getlist(key):
                    runtime_editables.append({
                        key: value
                    })
        mpi_uuid = request.args.get('mpi_uuid')
        pending_launch = launch_mpi(mpi_uuid, app_name, runtime_editables,current_user)
        return redirect('/')

    mpi_uuid = request.args.get('mpi_uuid')
    runtime_editables = get_runtime_editables(mpi_uuid, current_user)
    return render_template('marketplace/deploy.html', segment=['virtual_machines'], runtime_editables=runtime_editables)

app/vms/__init__.py
from flask import Blueprint

blueprint = Blueprint('vms',
                      __name__,
                      url_prefix='/vms')

from . import views

app/vms/views.py
from flask import render_template, request, current_app, make_response, redirect
from flask_login import login_required, current_user
from wtforms.fields.core import UnboundField
from . import blueprint
from .utils import list_deployed_vms, get_vm_details
from constants import NTNX_COOKIE


@blueprint.route('/')
@login_required
def index():
    deployed_vms = list_deployed_vms(current_user)
    return render_template('vms/index.html', segment=['virtual_machines'], vms=deployed_vms)


@blueprint.route('/details', methods=['GET'])
@login_required
def details():
    vmuuid = request.args.get('vm_uuid')
    console_access = request.args.get('console')
    vm_details = get_vm_details(vmuuid, current_user)
    if console_access == 'true':
        return render_template('vms/details.html', segment=['virtual_machines','console'], vm_details=vm_details, vm_uuid=vmuuid)
    else:
        return render_template('vms/details.html', segment=['virtual_machines'], vm_details=vm_details, vm_uuid=vmuuid)


@blueprint.route('/console/<vm_uuid>', methods=['GET'])
@login_required
def console(vm_uuid):
    vm_details = get_vm_details(vm_uuid, current_user)
    cluster_uuid = vm_details['cluster_reference']['uuid']
    console_url = f'/console/lib/noVNC/vnc_auto.html?path=vnc/vm/{vm_uuid}/proxy' \
                  f'&uuid={vm_uuid}&title={vm_uuid}&attached=true&hypervisorType=kKvm' \
                  f'&controllerVm=false&vmName={vm_uuid}&noV1Access=true&useV3=true' \
                  f'&isXi=false&clusterId={cluster_uuid}'
    resp = make_response(redirect(console_url))
    resp.set_cookie(NTNX_COOKIE, current_user.cookie, current_user.expiry_timedelta)
    return resp
    

app/templates/dashboard/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- New task button -->
    {% if current_user.is_consumer %}
        <div class="d-flex align-items-left">
            <div class="py-4">
                <div class="dropdown">
                    <button class="btn btn-gray-800 d-inline-flex align-items-center me-2 dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                        New Task
                    </button>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-start mt-2 py-1">
                        <a class="dropdown-item d-flex align-items-center" href="{{ url_for('dashboard.taskselect', task='vm')}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="dropdown-icon text-gray-400 me-2" viewBox="0 0 20 20"><path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/></svg>
                            New Virtual Machine
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="{{ url_for('dashboard.taskselect', task='network')}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="dropdown-icon text-gray-400 me-2" viewBox="0 0 20 20"><path d="M2 2a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h5.5v3A1.5 1.5 0 0 0 6 11.5H.5a.5.5 0 0 0 0 1H6A1.5 1.5 0 0 0 7.5 14h1a1.5 1.5 0 0 0 1.5-1.5h5.5a.5.5 0 0 0 0-1H10A1.5 1.5 0 0 0 8.5 10V7H14a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2zm.5 3a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm2 0a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1z"/></svg>
                            Add Network
                        </a>
                        {% if current_user.is_admin %}
                            <a class="dropdown-item d-flex align-items-center" href="{{ url_for('dashboard.taskselect', task='user')}}">
                                <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"></path></svg>
                                Add User
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="card border-light shadow-sm">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="h5">Deployed Applications</div>
                </div>
                {% if apps|length > 0 %}
                    <div class="col text-end">
                        Count: {{ apps|length }}
                    </div>
                {% endif %}

            </div>
        </div>
        <div class="table-responsive">
            <table class="table align-items-center table-flush">
                <thead class="thead-light">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">State</th>
                    <th scope="col">Created On</th>
                </tr>
                </thead>
                <tbody>
                {% for app in apps %}
                    <tr>
                        <th scope="row">{{ app.name }}</th>
                        <td>{{ app.state }}</td>
                        <td>{{ app.creation_time.strftime('%Y-%m-%d %H:%m') }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if usage.enabled=='true' %}
    <div class="card border-light shadow-sm">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="h5">
                        Resource Usage
                    </div>
                    
                    <div class="container">
                        <div class="d-flex justify-content-between">
                            <div></div>
                            <div>max vCPU: {{ usage.reserved_vcpu }} vCPU</div>
                        </div>
                        <div class="progress" style="height: 20px;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{usage.utilized_vcpu_percentage}}"
                            aria-valuemin="0" aria-valuemax="100" style="width:{{usage.utilized_vcpu_percentage}}%">
                                {{ usage.utilized_vcpu }} vCPU
                            </div>
                        </div>
                        
                    </div>
                    <div class="container">
                        <div class="d-flex justify-content-between">
                            <div></div>
                            <div>max Memory: {{ usage.reserved_memory }} GB</div>
                        </div>
                        <div class="progress" style="height: 20px;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{usage.utilized_memory_percentage}}"
                            aria-valuemin="0" aria-valuemax="100" style="width:{{usage.utilized_memory_percentage}}%">
                                {{ usage.utilized_memory }} GB
                            </div>
                            </div>
                    </div>
                    <div class="container">
                        <div class="d-flex justify-content-between">
                            <div></div>
                            <div>max Storage: {{ usage.reserved_disk }} GB</div>
                        </div>
                        <div class="progress" style="height: 20px;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{usage.utilized_disk_percentage}}"
                            aria-valuemin="0" aria-valuemax="100" style="width:{{usage.utilized_disk_percentage}}%">
                                {{ usage.utilized_disk }} GB
                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
{#    <div class="row">#}
{#        <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">#}
{#            <p class="mb-0 text-center text-lg-start">#}
{#                <a class="text-primary fw-normal" href="https://github.com/halsayed/calm-dashboard" target="_blank">Calm Dashboard</a>#}
{#            </p>#}
{#        </div>#}
{#        <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">#}
{#            <!-- List -->#}
{#            <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">#}
{#                <li class="list-inline-item px-0 px-sm-2">#}
{#                    <a target="_blank" #}
{#                       href="https://appseed.us/admin-dashboards/flask-dashboard-volt">Flask Volt Dashboard</a>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
</footer>

app/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
    <div class="container-fluid px-0">
        <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
            <div class="d-flex align-items-center">
            </div>

            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center">
                <li class="nav-item dropdown ms-lg-3">
                    <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="media d-flex align-items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="gray" class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                            </svg>
                            <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                            <span class="mb-0 font-small fw-bold text-gray-900">
                                <strong>
                                    {% if current_user.name %}
                                        {{ current_user.name }}
                                    {% else %}
                                        {{ current_user.username }}
                                    {% endif %}
                                </strong>
                            </span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
                        <a class="dropdown-item d-flex align-items-center" href="/settings.html">
                            <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path></svg>
                            My Profile
                        </a>
                        <div role="separator" class="dropdown-divider my-1"></div>
                        <a class="dropdown-item d-flex align-items-center" href="{{ url_for('auth.logout') }}">
                            <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/includes/scripts.html
<!-- Core -->
<script src="/static/assets/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Vendor JS -->
<script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Slider -->
<script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>

<!-- Smooth scroll -->
<script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<!-- Charts -->
<script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
<script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

<!-- Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Sweet Alerts 2 -->
<script src="/static/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Notyf -->
<script src="/static/assets/vendor/notyf/notyf.min.js"></script>

<!-- Simplebar -->
<script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="/static/assets/js/volt.js"></script>

app/templates/includes/sidebar.html
<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
        <ul class="nav flex-column pt-3 pt-md-0">

            <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="/" class="nav-link">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                  </span>
                    <span class="sidebar-text">Dashboard</span>
                </a>
            </li>
            <li class="nav-item {% if 'virtual_machines' in segment %} active {% endif %}">
                <a href="/vms" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="icon icon-xs me-2" viewBox="0 0 20 20">
                        <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
                    </svg>
                    <span class="sidebar-text">Virtual Machines</span>
                </a>
            </li>
            <li class="nav-item {% if 'networks' in segment %} active {% endif %}">
                <a href="/settings.html" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="icon icon-xs me-2" viewBox="0 0 20 20">
                        <path d="M4.5 5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zM3 4.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2H8.5v3a1.5 1.5 0 0 1 1.5 1.5h5.5a.5.5 0 0 1 0 1H10A1.5 1.5 0 0 1 8.5 14h-1A1.5 1.5 0 0 1 6 12.5H.5a.5.5 0 0 1 0-1H6A1.5 1.5 0 0 1 7.5 10V7H2a2 2 0 0 1-2-2V4zm1 0v1a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1zm6 7.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5z"/>
                    </svg>
                    <span class="sidebar-text">Networks</span>
                </a>
            </li>
            {% if current_user.is_admin %}
            <li class="nav-item {% if 'users' in segment %} active {% endif %}">
                <a href="/settings.html" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="icon icon-xs me-2" viewBox="0 0 20 20">
                        <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
                    </svg>
                    <span class="sidebar-text">Users</span>
                </a>
            </li>
            {% endif %}
            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
            <li class="nav-item">
                <a href="https://appseed.us/admin-dashboards/flask-dashboard-volt" target="_blank"
                   class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                  </span>
                    <span class="sidebar-text">Help</span>
                </a>
            </li>
            <li class="nav-item">
                <a target="_blank"
                   href="{{ url_for('auth.logout') }}"
                   class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="icon icon-xs me-2" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                        <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                    </svg>
                  </span>
                    <span class="sidebar-text">Logout</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

app/templates/marketplace/index.html
{% extends "layouts/base.html" %}

{% block title %} Marketplace {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="card border-light shadow-sm">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="h5">Available Items</div>
                </div>
                {% if mpi_list|length > 0 %}
                    <div class="col text-end">
                        Count: {{ mpi_list|length }}
                    </div>
                {% endif %}

            </div>
        </div>
        <div class="table-responsive">
            <table class="table align-items-center table-flush">
                <thead class="thead-light">
                <tr>
                    <th scope="col">Name</th>
                </tr>
                </thead>
                <tbody>
                {% for mpi in mpi_list %}
                    <tr>
                        <th scope="row">
                        <a href="/marketplace/deploy?mpi_uuid={{ mpi.uuid }}">{{ mpi.name }}</a></th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/vms/details.html
{% extends "layouts/base.html" %}

{% block title %} Details {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% if 'console' not in segment %}
    <div class="card border-light shadow-sm">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="h5">My VM Details</div>
                </div>
                <div>
                    {{ vm_details }}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% if 'console' in segment %}
    <div class="card border-light shadow-sm">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="row">
                    <div class="h6">Console</div>
                </div>
                <div class="ratio ratio-4x3">
                    <iframe src="{{ url_for('vms.console', vm_uuid=vm_uuid) }}"></iframe>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}